changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Security
      labels:
        - security
    - title: New Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Deprecated
      labels:
        - deprecation
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
