name: CI
on: [push]
jobs:
  build-and-test:
    name: "Run Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run unit tests
        run: |
          poetry run pytest --junit-xml="output/unit-tests.xml" --cov --cov-report="xml:output/coverage.xml"
      - name: Install SpamAssassin
        run: sudo apt-get -y install spamassassin
      - name: Run integration tests
        run: |
          poetry run pytest -m integration --junit-xml="output/integration-tests.xml"
      - name: Run mypy
        run: poetry run mypy aiospamc --junit-xml output/mypy-tests.xml
      - name: Run black
        run: poetry run black --check --diff --color .
      - name: Run interrogate
        run: poetry run interrogate
      - name: Publish test results
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: results-${{ matrix.python }}
          path: output/**
      - name: Package
        if: ${{ matrix.python == '3.9' }}
        run: poetry build -n
      - name: Publish package
        if: ${{ matrix.python == '3.9' }}
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: dist/
  publish:
    name: "Publish reports"
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: results-3.9
      - run: ls -R
      - uses: codecov/codecov-action@v2
        name: Upload to Codecov
        if: always()
        with:
          files: coverage.xml
          flags: unittests
          verbose: true
      - uses: EnricoMi/publish-unit-test-result-action@v1
        name: Publish unit test results
        if: always()
        with:
          files: "*-tests.xml"