name: CI
on: [push]
jobs:
  quality:
    name: "Code Quality"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run mypy
        run: poetry run mypy aiospamc --junit-xml output/mypy-tests.xml
      - name: Run black
        run: poetry run black --check --diff --color .
      - name: Run interrogate
        run: poetry run interrogate
      - name: Publish test results
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: quality-${{ matrix.python }}
          path: output/**
  build-and-unit-tests:
    name: "Run Unit Tests"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ['3.6', '3.7', '3.8', '3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run unit tests
        run: |
          poetry run pytest --junit-xml="output/unit-tests.xml" --cov --cov-report="xml:output/coverage.xml"
      - name: Install SpamAssassin
        run: sudo apt-get -y install spamassassin
      - name: Run integration tests
        run: |
          poetry run pytest -m integration --junit-xml="output/integration-tests.xml"
      - name: Publish test results
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: results-${{ matrix.python }}
          path: output/**
      - name: Package
        if: ${{ matrix.python == '3.9' }}
        run: poetry build -n
      - name: Publish package
        if: ${{ matrix.python == '3.9' }}
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: dist/
  integration-tests:
    name: "Run Integration Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Install SpamAssassin
        run: sudo apt-get -y install spamassassin
      - name: Run integration tests
        run: |
          poetry run pytest -m integration --junit-xml="output/integration-tests.xml"
      - name: Publish test results
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: integration
          path: output/**
  publish:
    name: "Publish reports"
    runs-on: ubuntu-latest
    needs: [quality, build-and-unit-tests, integration-tests]
    if: success() || failure()
    steps:
      - uses: actions/download-artifact@v2
      - uses: EnricoMi/publish-unit-test-result-action@v1
        name: Publish unit test results
        with:
          files: |
            **/*-tests.xml
      - uses: codecov/codecov-action@v2
        name: Upload to Codecov
        with:
          files: |
            **/coverage.xml
          flags: unittests
