name: Continuous integration
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run unit tests
        run: |
          poetry run pytest --junit-xml="output/unit-test-results.xml" --cov --cov-report="xml:output/coverage.xml"
      - name: Publish unit test results
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-results
          path: output/unit-test-results.xml
      - name: Publish code coverage
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: output/coverage.xml
      - name: Run mypy
        run: poetry run mypy aiospamc
      - name: Run black
        run: poetry run black --check .
      - name: Run interrogate
        run: poetry run interrogate
