name: Integration tests
on:
  push:
    branches: [ development, main, integration-test-container ]
  pull_request:
    branches: [ development ]
  schedule:
    - cron: '0 0 * * 5'
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    name: "Run Integration Tests"
    strategy:
      matrix:
        spamassassin: ["3.4.6", "4.0.0"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Download SpamAssasin
        run: |
          curl -s https://dlcdn.apache.org//spamassassin/source/Mail-SpamAssassin-${{ matrix.spamassassin }}.tar.bz2 -o spamassassin.tar.bz2
          tar -xvjf spamassassin.tar.bz2
      - name: Build & Install SpamAssassin
        working-directory: ./Mail-SpamAssassin-${{ matrix.spamassassin }}
        run: |
          sudo apt install -y perl libssl-dev libhtml-parser-perl libnet-dns-perl libnetaddr-ip-perl debhelper-compat libberkeleydb-perl netbase libdbi-perl libdbd-mysql-perl libbsd-resource-perl libio-string-perl libtext-diff-perl
          sudo apt install -y adduser libarchive-tar-perl libhttp-date-perl libmail-dkim-perl libnet-dns-perl libnetaddr-ip-perl libsocket6-perl libio-socket-ssl-perl
          perl Makefile.PL BUILD_SPAMC=no ENABLE_SSL=yes CONTACT_ADDRESS=aiospamc-ci@example.org
          make
          sudo make install
          perl
      - run: sudo sa-update
      - run: spamd --version
      - name: Run integration tests
        run: |
          poetry run pytest -m integration --junit-xml="output/integration-tests.xml" --spamd-process-timeout 30
      - name: Publish test results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: output/**
