name: Release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
jobs:
  release:
    needs: [code-style, tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.10
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Publish package
        run: poetry publish --dry-run -n
