name: Release Artifacts
on: [release]
jobs:
  upload:
    name: "Upload release artifacts"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip --disable-pip-version-check
          pip install poetry --disable-pip-version-check
      - name: Install dependencies
        run: poetry install --no-dev
      - name: Publish package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: dist/
      - name: Publish to PyPI
        run: poetry publish --dry-run -n
      - run: gh release upload ${{ github.event.release.tag_name }} dist/*
