name: Release
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    name: "Upload release artifacts"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Save tag
        run: |
          tag="$(git describe --tags --abbrev=0)"
          echo 'TAG='$tag >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip --disable-pip-version-check
          pip install poetry --disable-pip-version-check
      - name: Install dependencies
        run: poetry install
      - name: Run unit tests
        run: poetry run pytest --junit-xml="output/unit-tests.xml"
      - name: Install SpamAssassin
        run: sudo apt-get -y install spamassassin
      - name: Run integration tests
        run: poetry run pytest -m integration --junit-xml="output/integration-tests.xml"
      - name: Publish test results
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: output/**
      - name: Build package
        run: poetry build
      - name: Publish package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: dist/
      - name: Publish to PyPI
        run: |
          poetry config pypi-token.pypi $POETRY_PYPI_TOKEN_PYPI
          poetry publish -n
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
      - name: GitHub release
        run: gh release create "$TAG" --generate-notes dist/*
        env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
