name: Unit tests prerelease
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'
env:
  python-version: '3.14-dev'
jobs:
  unit-tests:
    name: "Run unit tests for Python pre-release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        run: pipx install uv
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.python-version }}
      - name: Install dependencies
        run: uv sync
      - name: Run unit tests
        run: >
          uv run pytest
          --junit-xml="output/unit-tests.xml"
          --cov
          --cov-report="xml:output/coverage.xml"
          --cov-report="html:output/htmlcov"
      - name: Publish test results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ env.python-version }}
          path: output/**
  status:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: "Unit Test Status"
    needs: unit-tests
    steps:
      - name: Check test matrix status
        if: ${{ needs.unit-tests.result != 'success' }}
        run: exit 1
