name: Unit tests prerelease
on:
  schedule:
    - cron: '0 0 * * 5'
jobs:
  unit-tests:
    name: "Run Unit Tests"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12-dev'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Run unit tests
        run: >
          poetry run pytest
          --junit-xml="output/unit-tests.xml"
          --cov
          --cov-report="xml:output/coverage.xml"
          --cov-report="html:output/htmlcov"
      - name: Publish test results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.python }}
          path: output/**
  status:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: "Unit Test Status"
    needs: unit-tests
    steps:
      - name: Check test matrix status
        if: ${{ needs.unit-tests.result != 'success' }}
        run: exit 1
