name: Weekly
on:
  schedule:
    - cron: '0 0 * * 5'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.9'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run mypy
        run: poetry run mypy aiospamc
      - name: Run black
        run: poetry run black --check .
      - name: Run interrogate
        run: poetry run interrogate
      - name: Run unit tests
        run: |
          poetry run pytest --junit-xml="output/unit-tests.xml" --cov --cov-report="xml:output/coverage.xml"
      - uses: EnricoMi/publish-unit-test-result-action@v1
        name: Publish unit test results
        if: always()
        with:
          files: output/**/*-tests.xml
      - uses: codecov/codecov-action@v2
        name: Upload to Codecov
        if: always()
        with:
          files: output/coverage.xml
          flags: unittests
      - name: Install SpamAssassin
        run: sudo apt-get -y install spamassassin
      - name: Run unit tests
        run: |
          poetry run pytest -m integration --junit-xml="test-results/integration-tests.xml"
      - name: Publish integration test results
        uses: actions/upload-artifact@v2
        with:
          name: integration-test-results
          path: output/integration-tests.xml
      - name: Package
        run: poetry build -n
      - name: Publish package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: dist/
